#!/usr/bin/perl
use Flickr::API;
my $api = new Flickr::API({'key' => 'eac1c8300385dd45b79dacdf8bc95ad1', 'secret' => 'e4df254d2111beb8'});

while ( $photo_id = <STDIN> ){
	chomp $photo_id;
	print_url( $photo_id );
}

sub print_url {
	my $photo_id = shift;

	# http://www.flickr.com/services/api/flickr.photos.getSizes.html
	my $res = $api->execute_method('flickr.photos.getSizes', { 'photo_id' => $photo_id });

	my $urls;
	map {
		if ( exists $_->{attributes} ){
			$urls->{lc $_->{attributes}{label}} = $_->{attributes}{source};
		}
	} @{$res->{tree}{children}[1]{children}};

	printf "%s\n", $urls->{original} || $urls->{large} || $urls->{medium};
}

